// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Polaris = require("@shopify/polaris");

function SkeletonRessourceList(Props) {
  var length = Props.length;
  return React.createElement(Polaris.ResourceList, {
              items: $$Array.mapi((function (index, param) {
                      return index;
                    }), Caml_array.caml_make_vect(length, 0)),
              renderItem: (function (item) {
                  return React.createElement(Polaris.ResourceList.Item, {
                              id: String(item),
                              children: React.createElement(Polaris.SkeletonBodyText, {
                                    lines: 1
                                  })
                            });
                })
            });
}

var make = SkeletonRessourceList;

exports.make = make;
/* react Not a pure module */
