// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Polaris = require("@shopify/polaris");

function str(prim) {
  return prim;
}

function renderItem(item) {
  var shortcutActions = /* array */[{
      content: "Add to basket (+1)",
      onAction: (function (param) {
          console.log("Add " + item[/* name */1]);
          return /* () */0;
        })
    }];
  return React.createElement(Polaris.ResourceList.Item, {
              id: String(item[/* id */0]),
              shortcutActions: shortcutActions,
              persistActions: true,
              children: null
            }, React.createElement("h3", undefined, React.createElement("strong", undefined, item[/* name */1])), React.createElement("div", undefined, item[/* description */2]), React.createElement("br", undefined), React.createElement("p", undefined, "Unit price: ", React.createElement("strong", undefined, " " + (item[/* price */3].toString() + "€"))));
}

function App(Props) {
  var match = React.useReducer((function (state, _action) {
          return state;
        }), /* record */[
        /* items : :: */[
          /* record */[
            /* id */0,
            /* name */"Product A",
            /* description */"Lorem ipsum dolor sit, amet consectetur",
            /* price */12.0,
            /* tax */20.0
          ],
          /* :: */[
            /* record */[
              /* id */1,
              /* name */"Product B",
              /* description */"Lorem ipsum dolor sit, amet consectetur",
              /* price */13.0,
              /* tax */5.5
            ],
            /* [] */0
          ]
        ],
        /* cart : record */[/* products : :: */[
            /* record */[
              /* productId */0,
              /* quantity */2
            ],
            /* :: */[
              /* record */[
                /* productId */1,
                /* quantity */3
              ],
              /* [] */0
            ]
          ]]
      ]);
  var match$1 = match[0];
  return React.createElement(Polaris.AppProvider, {
              children: React.createElement(Polaris.Page, {
                    title: "React Shopping Cart",
                    children: React.createElement(Polaris.Layout, {
                          children: null
                        }, React.createElement(Polaris.Layout.Section, {
                              children: React.createElement(Polaris.Card, {
                                    children: React.createElement(Polaris.ResourceList, {
                                          resourceName: {
                                            singular: "Customer",
                                            plural: "Customers"
                                          },
                                          items: Belt_List.toArray(match$1[/* items */0]),
                                          renderItem: renderItem
                                        })
                                  })
                            }), React.createElement(Polaris.Layout.Section, {
                              secondary: true,
                              children: React.createElement(Polaris.Card, {
                                    title: "Basket",
                                    primaryFooterAction: {
                                      content: "Pay now",
                                      loading: false
                                    },
                                    secondaryFooterAction: {
                                      content: "Cancel cart"
                                    },
                                    children: React.createElement(Polaris.Card.Section, {
                                          title: "Totals",
                                          children: React.createElement(Polaris.List, {
                                                type: "number",
                                                children: Belt_List.toArray(Belt_List.map(match$1[/* cart */1][/* products */0], (function (item) {
                                                            return React.createElement(Polaris.List.Item, {
                                                                        key: String(item[/* productId */0]),
                                                                        children: null
                                                                      }, React.createElement("span", undefined, "ID Produit = " + String(item[/* productId */0])), React.createElement("span", undefined, ", Qte = " + String(item[/* quantity */1])));
                                                          })))
                                              })
                                        })
                                  })
                            }))
                  })
            });
}

var make = App;

exports.str = str;
exports.renderItem = renderItem;
exports.make = make;
/* react Not a pure module */
