// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.js");
var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement(App.make, { }), "root");

/*  Not a pure module */
